### ISSUE TITLE
[6]  TCP chat server -> The messages should be encoded with Caesar Cipher

### ISSUE THREAD

**Issue by hetsonii** [kurogai/100-redteam-projects#40]
I would like to work on TCP chat server project. Can you please assign? 

also, UDP chat server with ROT13 has been completed [here](https://github.com/kurogai/100-redteam-projects/tree/master/Projects/8_%20UDP_server_ROT13_Cipher) but it shows incomplete in the README.

**Comment by kurogai** [comment]
You can work on existing projects, feel free!!
And thanks about the ROT13, i'll review it right now
