### ISSUE TITLE
Enquiry for pull request

### ISSUE THREAD

**Issue by reveng007** [kurogai/100-redteam-projects#9]
I made a LKM based rootkit named, [reveng_rtkit](https://github.com/reveng007/reveng_rtkit). Can it be added to this repo?
If so, how can I mention my my project repo link in the README.md file?
Actually, I'm little confussed.

**Comment by kurogai** [comment]
Hi, since there is no category about rootkits, please create one (like an list) and name it "Honorable Mentions" :)
Thank you <3

**Comment by reveng007** [comment]
Thank you for your approval!
Also thank you for maintaining such awesome repo.
